"""Generate an idempotent SQL seed script from /Users/kaviya/Desktop/App-dev/Borderless/Borderless GT.csv.

Reads the CSV, filters out the duplicate header rows that got concatenated
into the export, then emits ONE big INSERT ... ON CONFLICT (study_id) DO
UPDATE statement per row so the script is safe to re-run.

Output: scripts/seed_csv.sql (paste into DBeaver, or psql -f).
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

CSV_PATH = Path("/Users/kaviya/Desktop/App-dev/Borderless/Borderless GT.csv")
OUT_PATH = Path(__file__).resolve().parent / "seed_csv.sql"

SCHEMA = "rad_incubation"
TABLE = '"Study_Groundtruth"'
FQN = f'{SCHEMA}.{TABLE}'

# Column → SQL type-hint. Determines NULL/quote/cast handling.
#   'int'   → bare integer, '' → NULL
#   'bool'  → true/false, '' → NULL
#   'text'  → quoted string, '' → NULL
#   'ts'    → quoted timestamptz literal, '' → NULL
#   'jsonb' → quoted string cast ::jsonb, '' or '[]' → '[]'::jsonb
COLS: list[tuple[str, str]] = [
    ("study_id", "int"),          # PK
    ("report_id", "int"),
    ("study_iuid", "text"),
    ("modstudy", "text"),
    ("groundtruth_pathology", "text"),
    ("created_at", "ts"),
    ("updated_at", "ts"),
    ("modality", "text"),
    ("history", "text"),
    ("dicom_metadata", "text"),    # stored as text in the schema
    ("rules", "text"),             # stored as text in the schema
    ("is_complex", "bool"),
    ("main_pathologies", "jsonb"),
    ("incidental_findings", "jsonb"),
    ("classified_at", "ts"),
    ("old_study_iuid", "text"),
    ("category", "text"),
    ("observation", "text"),
    ("impression", "text"),
    ("age", "text"),
    ("case_type", "text"),
]


def _quote(s: str) -> str:
    # Dollar-quote — avoids escaping single quotes / backslashes / newlines.
    # Use a delimiter that's vanishingly unlikely to appear in the data.
    tag = "SG"
    while f"${tag}$" in s:
        tag += "X"
    return f"${tag}${s}${tag}$"


def _fmt(value: str, kind: str) -> str:
    v = value if value is not None else ""
    stripped = v.strip()
    if kind == "int":
        if stripped == "":
            return "NULL"
        return stripped
    if kind == "bool":
        if stripped == "":
            return "NULL"
        s = stripped.lower()
        if s in ("true", "t", "1"):
            return "true"
        if s in ("false", "f", "0"):
            return "false"
        raise ValueError(f"bad bool: {value!r}")
    if kind == "ts":
        if stripped == "":
            return "NULL"
        return f"{_quote(stripped)}::timestamptz"
    if kind == "jsonb":
        if stripped == "":
            return "'[]'::jsonb"
        return f"{_quote(stripped)}::jsonb"
    # text
    if v == "":
        return "NULL"
    return _quote(v)


def main() -> int:
    if not CSV_PATH.exists():
        print(f"CSV not found: {CSV_PATH}", file=sys.stderr)
        return 1

    with CSV_PATH.open("r", encoding="utf-8", errors="replace", newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    # Filter embedded header rows (study_id literal == 'study_id').
    clean_rows = [r for r in rows if (r.get("study_id") or "").strip() != "study_id"]

    print(f"Total rows in CSV: {len(rows)}", file=sys.stderr)
    print(f"After dropping embedded headers: {len(clean_rows)}", file=sys.stderr)

    seen = set()
    deduped: list[dict] = []
    duplicates: list[str] = []
    for r in clean_rows:
        sid = r["study_id"].strip()
        if sid in seen:
            duplicates.append(sid)
            continue
        seen.add(sid)
        deduped.append(r)
    if duplicates:
        print(f"WARN: {len(duplicates)} duplicate study_id rows dropped (kept first): "
              f"{duplicates[:5]}{'...' if len(duplicates) > 5 else ''}", file=sys.stderr)

    col_names = [c for c, _ in COLS]
    col_sql = ", ".join(col_names)
    update_set = ",\n  ".join(
        f"{c} = EXCLUDED.{c}"
        for c, _ in COLS
        if c != "study_id"  # don't overwrite the PK
    )

    parts: list[str] = []
    parts.append(
        "-- Generated by scripts/_generate_seed_csv.py\n"
        "-- Source: /Users/kaviya/Desktop/App-dev/Borderless/Borderless GT.csv\n"
        "-- Idempotent: re-running overwrites every column except study_id (PK).\n"
        "-- Run in a single transaction.\n"
        "BEGIN;\n"
    )

    for r in deduped:
        try:
            values = ", ".join(_fmt(r.get(c, ""), kind) for c, kind in COLS)
        except ValueError as e:
            print(f"SKIP study_id={r.get('study_id')!r}: {e}", file=sys.stderr)
            continue
        parts.append(
            f"INSERT INTO {FQN} ({col_sql})\n"
            f"VALUES ({values})\n"
            f"ON CONFLICT (study_id) DO UPDATE SET\n  {update_set};\n"
        )

    parts.append("COMMIT;\n")
    OUT_PATH.write_text("\n".join(parts), encoding="utf-8")
    size_kb = OUT_PATH.stat().st_size / 1024
    print(f"Wrote {OUT_PATH} ({size_kb:.1f} KB, {len(deduped)} rows)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
